[ids]

*
046d:c547
1d50:615e
046d:c547

[main]

f18 = 4
f17 = 5
mouse1 = 2
mouse2 = 1
numlock = calc
f20 = overload(f20, 3)

backspace = m
enter = comma
delete = backspace
capslock = enter

[alt]
scrollup = C-volumeup
scrolldown = C-volumedown

[f20]
scrollup = volumeup
scrolldown = volumedown
