[ids]

*
046d:c547
1d50:615e
046d:c547

[main]

f18 = f4
f17 = f5
# mouse1 = 2
# mouse2 = 1
numlock = calc
f20 = overload(f20, 3)
compose = layer(menu)
rightalt = layer(alt)

[alt]
scrollup = C-volumeup
scrolldown = C-volumedown
enter = enter

[meta]
scrollup = volumeup
scrolldown = volumedown

[menu]
scrollup = volumeup
scrolldown = volumedown

[f20]
scrollup = volumeup
scrolldown = volumedown
